### ISSUE TITLE
Update README to use standard CoZ format

### ISSUE THREAD

**Issue by AshRolls** [CityOfZion/neo-gui-wpf#1]

**Comment by justingaffney** [comment]
Is there a template somewhere for the standard CoZ format for README files? Or an example repo I can base the README format on?

**Comment by AshRolls** [comment]
Yup, check this one https://github.com/CityOfZion/neo-python . @revett is also a fanatical README zealot so you can ask him in slack for advice :)

**Comment by revett** [comment]
@AshRolls Haha 😂

@jlgaffney The original is [here](https://github.com/CityOfZion/neo-go-sdk) but most CoZ READMEs now follow a theme. Happy to answer any questions 👍
