### ISSUE TITLE
HomeViewModel is subscribed 3 times in the messageSubscriber

### ISSUE THREAD

**Issue by omarspx** [CityOfZion/neo-gui-wpf#105]
OnLoad implementation of HomeViewModel is called 3 times upon starting.

1:
In DialogManager.cs/CreateDialog(): loadable?.OnLoad()
2:
In DataContextBindingExtensions.cs / ProvideValue(): loadableViewModel.OnLoad();
3:
In App.xaml.cs / Initialize(): loadableDataContext?.OnLoad();

On the GUI, when I do Advanced > Invoke contract, the InvokeContractDialog is opened once, and reopen 2 times after that when I close the window.

**Comment by justingaffney** [comment]
This issue should be fixed now in the dev branch
