### ISSUE TITLE
ImportCustomContractViewModel doesn't have a RelatedAccounts obervable collection

### ISSUE THREAD

**Issue by omarspx** [CityOfZion/neo-gui-wpf#106]
ImportCustomContractView has a RelatedAccount combobox bound to RelatedAccounts, but RelatedAccounts doesn't exist in ImportCustomContractViewModel.

I can create a custom contract without adding a Related Account. Is it still needed?

**Comment by justingaffney** [comment]
No the related account is not needed. Thanks for pointing this out, I'll remove it from ImportCustomContractView

**Comment by justingaffney** [comment]
The related account combobox has been removed from ImportCustomContractView
