### ISSUE TITLE
Asset page display error

### ISSUE THREAD

**Issue by Ray-77** [CityOfZion/neo-gui-wpf#17]
Can't find the assets name on the page of asset.

![assetname](https://user-images.githubusercontent.com/17636881/32474607-55a057b2-c3a8-11e7-82fb-650c89a54072.png)

**Comment by Ray-77** [comment]
And repeatedly display.
![repeat](https://user-images.githubusercontent.com/17636881/32474718-dddf595c-c3a8-11e7-9a00-dd7b68c5b9ec.png)

**Comment by justingaffney** [comment]
This issue should be fixed now. Please let me know if it is still occurring for you

**Comment by Ray-77** [comment]
This issue has shown up again.
![asset](https://user-images.githubusercontent.com/17636881/32928054-15f14b54-cb8b-11e7-931f-ceeded19d396.png)
