### ISSUE TITLE
Add MIT Licence

### ISSUE THREAD

**Issue by AshRolls** [CityOfZion/neo-gui-wpf#2]

**Comment by justingaffney** [comment]
The repo already has the original MIT license file added by Erik, what else is required?

**Comment by AshRolls** [comment]
Hmm yes, I see the file. GitHub isn't picking it up though for some reason.

**Comment by justingaffney** [comment]
Yeah I noticed that too, I might try removing and adding it again to try get GitHub to recognise it

**Comment by justingaffney** [comment]
I tried removing LICENSE file and adding it again using GitHub's license template, but it didn't work. I've let GitHub support know about the problem

**Comment by AshRolls** [comment]
I notice some README have the .md file extension, so you could try renaming the file?

**Comment by justingaffney** [comment]
Yeah I tried that as well, it didn't work. I even tried adding a name just in case that was causing it to not be recognised, didn't work either. Hopefully GitHub support can help out

**Comment by justingaffney** [comment]
GitHub support have fixed the problem, I think this issue can be closed
