### ISSUE TITLE
The transaction is unconfirmed on the page of "transaction record", which actually is confirmed.

### ISSUE THREAD

**Issue by Ray-77** [CityOfZion/neo-gui-wpf#29]
The transaction has been confirmed,
![ud](https://user-images.githubusercontent.com/17636881/32599418-71d11fb8-c577-11e7-98c3-90fa1fd59397.png)

but it shows
![tx](https://user-images.githubusercontent.com/17636881/32599425-787bb792-c577-11e7-9c59-050d2777ac1c.png)

**Comment by justingaffney** [comment]
Did you create the transaction using this application? If you did use this application to create the transaction, did you close the application after making the transaction and start the application again?

**Comment by justingaffney** [comment]
I think this issue has been fixed by this PR https://github.com/CityOfZion/neo-gui-wpf/pull/30. Could you please check the transaction confirmations update correctly?

**Comment by Ray-77** [comment]
![nf](https://user-images.githubusercontent.com/17636881/32652516-7a4dfc56-c63f-11e7-9071-15fa3c335595.png)
I can't open it now after updating the code.

**Comment by Ray-77** [comment]
![4 7](https://user-images.githubusercontent.com/17636881/32652656-efb2d9b2-c63f-11e7-86bc-8c69258efef8.png)

**Comment by justingaffney** [comment]
Do you have .NET Framework 4.7 installed?
