### ISSUE TITLE
Handling of the message SignTransactionAndShowInformationMessage in HomeViewModel is missplace

### ISSUE THREAD

**Issue by aboimpinto** [CityOfZion/neo-gui-wpf#39]
The handling of this message dependent on the WalletController and the BlockChainController to push the transaction. 
This method also show InformationBox regarding the outcome of the operation therefore this need to receive the IDialogHelper and I'm sure the BlockChainController and WalletController should have this dependency. They should not have access to the UI thread, not to naviage to any modal or not modal windows or show any information.

I believe this controllers should publish message with the information and be catched by any active class that handle it showing the information or open a dialog

**Comment by justingaffney** [comment]
This message is now handled by the WalletController class
