### ISSUE TITLE
"Process.Start" calls need to be abstract

### ISSUE THREAD

**Issue by aboimpinto** [CityOfZion/neo-gui-wpf#40]
In order to improve testability, the calls "Process.Start" that has been used to open an URL Address need to be abstract with an interface.

**Suggestion:** 
Create the interface IUrlNavigationHelper with the method "Navigate(Uri uri)"

this interface should be injected in the ViewModels that need to navigate to an URL and this call can be tested

**Comment by aboimpinto** [comment]
The implementation was to create an interface called: IExternalProcessHelper with the method 
void OpenInExternalBrowser(string url);

with this names is more explicit what is the responsibility of this class.

**Comment by justingaffney** [comment]
Fixed by PR #47
