### ISSUE TITLE
BlockChainController doesn't connect to any peer

### ISSUE THREAD

**Issue by aboimpinto** [CityOfZion/neo-gui-wpf#41]
After wiring up the BlockChainController to the application, there should be missing something because doesn't connect to any peer therefore don't download blocks.

**Comment by justingaffney** [comment]
I have built the application using the dev branch and the BlockChainController and it is receiving new blocks from peers. It might be a network or firewall issue that's preventing your application instance from receiving blocks from peers

**Comment by aboimpinto** [comment]
Looks like that it's working ... Just don't start right away!
