### ISSUE TITLE
CreateNewKey of CreateNewAddress method

### ISSUE THREAD

**Issue by aboimpinto** [CityOfZion/neo-gui-wpf#43]
Fowling the naming of the NEO assemblies, the method in the WalletController should be CreateNewKey, but, looks like that outcome is a new NEO address.

it is key or address?

**Comment by justingaffney** [comment]
The code in the Wallet.CreateKey method looks like it generates a new random private key and contructs a new KeyPair instance containing the private key and its derived public key. This key pair is then stored in the wallet instance's keys dictionary. The ScriptHash property seems to be a hash of the KeyPair's public key, and an address is a base 58 encoded version of a script hash.

So I think it does create a new key and the method name is accurate, and an address is derived from the new key
