### ISSUE TITLE
Compiling the project is giving a XAMARIN error

### ISSUE THREAD

**Issue by aboimpinto** [CityOfZion/neo-gui-wpf#5]
hello
I got this project and try to compile local and I get this

![image](https://user-images.githubusercontent.com/1231687/31881245-469a126a-b7e3-11e7-9323-d86fa66a02d3.png)

I could not find any reference to Xamarin and didn't found any PCL in the solution.

what  could be the issue?
Paulo Aboim Pinto

**Comment by aboimpinto** [comment]
There is some references to xamarin in the project file. I remove it and could compile with no problem.

can you please clean up this references?

**Comment by justingaffney** [comment]
Yeah that reference should not be there, I'll remove it
