### ISSUE TITLE
Application don't download the Blockchain

### ISSUE THREAD

**Issue by aboimpinto** [CityOfZion/neo-gui-wpf#6]
Finally I could start the app and I get this

![image](https://user-images.githubusercontent.com/1231687/31888237-891cc9e4-b7fb-11e7-9d47-405d43c4ade6.png)

Looks like that is sync with blockchain, the connected number goes up and down but the Height never change.
Don't know if there is an issue with my Office limitation or if there is communication issue.

How do I know where I'm connecting? Neo Network or test network?

Paulo

**Comment by justingaffney** [comment]
It does seem to take a while to start receiving blocks from other connected nodes. However the block synchronisation logic is not defined in this repo, and it still does basically the same thing as the original Winforms code. I think that logic is in one of the NEO core repos, I'll need to double check which one

**Comment by justingaffney** [comment]
Are you still unable to receive any blocks?

**Comment by aboimpinto** [comment]
Yes, looks like this is a problem that I have in the office. At home works fine. 

this issue can be close.
