### ISSUE TITLE
CX509PrivateKey has wrong properties

### ISSUE THREAD

**Issue by aboimpinto** [CityOfZion/neo-gui-wpf#7]
When I compile the solution I get this error 

![image](https://user-images.githubusercontent.com/1231687/31892975-98fe1836-b80a-11e7-9036-ac698a51e042.png)

How can I have a different version? This is obtain from nuget.

Paulo

**Comment by justingaffney** [comment]
Huh that's strange it compiles fine for me, thanks I'll take a look

**Comment by justingaffney** [comment]
I can't reproduce this issue, is it still occurring when compiling?

**Comment by aboimpinto** [comment]
I think this problem was happening in 32bits. I'm using AnyCPU configuration and I don't get this issue.
